
name: 'H-Extend'

on:
  #push:
  schedule:
    # UTC (国内 UTC+8)
     - cron: '25 17 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    #runs-on: macos-latest
    runs-on: macos-12

    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
          
        - name: 'Update Chrome'           
          run: |
            brew reinstall --cask google-chrome
            
        - name: 'Set Cloudflare WARP'           
          run: |
            brew install wgcf
            brew install wireguard-tools
            wgcf register --accept-tos
            wgcf generate
            sudo mkdir /etc/wireguard/
            sudo cp wgcf-profile.conf /etc/wireguard/wgcf.conf
            wg-quick up wgcf
            echo 
            curl ip.p3terx.com
            
        - name: 'Install requirements'
          run: |
            pip3 install -r VPS/requirements.txt
            pip3 install undetected-chromedriver
            yes | pip3 uninstall selenium
            pip3 install selenium==4.2.0
            
        - name: 'Renew'
          env:
            USER_ID_H_1: ${{ secrets.USER_ID_H_1 }}
       #     USER_ID_H_2: ${{ secrets.USER_ID_H_2 }}
        #    USER_ID_H_3: ${{ secrets.USER_ID_H_3 }}
         #   USER_ID_H_4: ${{ secrets.USER_ID_H_4 }}
          #  USER_ID_H_5: ${{ secrets.USER_ID_H_5 }}
  #          USER_ID_H_6: ${{ secrets.USER_ID_H_6 }}
   #         USER_ID_H_7: ${{ secrets.USER_ID_H_7 }}
    #        USER_ID_H_8: ${{ secrets.USER_ID_H_8 }}
            PASS_WD_H_1: ${{ secrets.PASS_WD_H_1 }}
     #       PASS_WD_H_2: ${{ secrets.PASS_WD_H_2 }}
      #      PASS_WD_H_3: ${{ secrets.PASS_WD_H_3 }}
       #     PASS_WD_H_4: ${{ secrets.PASS_WD_H_4 }}
        #    PASS_WD_H_5: ${{ secrets.PASS_WD_H_5 }}
         #   PASS_WD_H_6: ${{ secrets.PASS_WD_H_6 }}
          #  PASS_WD_H_7: ${{ secrets.PASS_WD_H_7 }}
            #PASS_WD_H_8: ${{ secrets.PASS_WD_H_8 }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}

          run: |
            python3 VPS/main-h.py
